# Generated by Django 5.1.6 on 2025-02-28 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
